Error-fix: Grade updated to 6.9
Fixed the following error due to grade 6.8 -
Error: INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl47966781.tmp/0_app-debug: AndroidManifest.xml'